In [1]:
import numpy as np

In [2]:
prices = np.array([
    [15,3,23,6,0],
    [1,4,17,8,0],
    [9,13,14,7,0],
],dtype=int)
have = np.array([70,47,38])
need = np.array([20,30,40,50,15])
north_west = np.array([
    [20,30,20,00,00],
    [00,00,20,27,00],
    [00,00,00,23,15]
])

In [3]:
north_west = np.array([
    [20,30,20,00,00],
    [00,00,20,27,00],
    [00,00,00,23,15]
])
print('Have\n')
for i in range(0,3):
    print(f"{have[i]} : {np.sum(north_west[i,:])}")
print('\nNeed\n')
for i in range(0,5):
    print(f"{need[i]} : {np.sum(north_west[:,i])}")
        
U = np.zeros(3,int)
V = np.zeros(5,int)

pot = np.zeros((3,5),int)

for i in range(0,3):
    for j in range(0,5):
        if(north_west[i,j] != 0):
            pot[i,j] = prices[i,j]
            if(i==0):
                V[j] = prices[i,j]
            elif(U[i] == 0 and i != 0):
                U[i] = prices[i,j] - V[j]
            elif(V[j] == 0):
                V[j] = prices[i,j] - U[i] 
print(pot,U,V,sep='\n', end='\n\n')

delt = np.zeros((3,5),int)
for i in range(0,3):
    for j in range(0,5):
        delt[i,j] = prices[i,j] - U[i] - V[j]
print(delt)



Have

70 : 70
47 : 47
38 : 38

Need

20 : 20
30 : 30
40 : 40
50 : 50
15 : 15
[[15  3 23  0  0]
 [ 0  0 17  8  0]
 [ 0  0  0  7  0]]
[ 0 -6 -7]
[15  3 23 14  7]

[[ 0  0  0 -8 -7]
 [-8  7  0  0 -1]
 [ 1 17 -2  0  0]]
